### ISSUE TITLE
Ambiguous text in Section 2.1

### ISSUE THREAD

**Issue by hosamaly** [oauth-wg/oauth-v2-1#134]
The following text, which is under Section 2.1: Client Types, is ambiguous:

> This might by the pre-requisite to use client policy and metadata in the course of processing this flow. 

Source: https://github.com/oauth-wg/oauth-v2-1/blob/52abd5ba65663d7dc7ffbd013f0d00e8964ccbce/draft-ietf-oauth-v2-1.md?plain=1#L653-L654

**Comment by aaronpk** [comment]
Thank you, yes this is confusing. Will fix in the next revision.
