### ISSUE TITLE
Ensure Security BCP recommendations are all incorporated into 2.1

### ISSUE THREAD

**Issue by aaronpk** [oauth-wg/oauth-v2-1#136]

**Comment by danielfett** [comment]
Table for tracking the mapping: https://docs.google.com/spreadsheets/d/15NC1af2J9jMPqjPUxJgwMYjR-L_nSH-yqPvGHL_EZag/edit?usp=sharing

**Comment by danielfett** [comment]
Collecting new PRs in BCP that might be relevant for 2.1:

1. In-browser communication: https://github.com/oauthstuff/draft-ietf-oauth-security-topics/pull/64

**Comment by aaronpk** [comment]
* [ ] https://github.com/oauthstuff/draft-ietf-oauth-security-topics/issues/70
