### ISSUE TITLE
Use of 'permissions' term in refresh token section

### ISSUE THREAD

**Issue by jogu** [oauth-wg/oauth-v2-1#164]
https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-09.html#section-1.3.2 says:

> access tokens may have a shorter lifetime and fewer permissions than authorized by the resource owner

I've recently had some in depth conversations about what "permissions" here means. This is the only use of 'permissions' [in this way] in the whole document, and I don't think there's some special thing that's different in the refresh token grant that means we should be using a different word. I think it might be a small improvement to use the same terms as used elsewhere in the document - other words that are already used are "access range", "scopes", "scope-token" and "privileges".

Changing "permissions" to "privileges" seems like it would probably be the most consistent with the rest of the spec.

**Comment by aaronpk** [comment]
Agreed, I think that's an easy fix. "privileges" is used in a lot of other places already.
