### ISSUE TITLE
7.X Stateless tokens and key rotation

### ISSUE THREAD

**Issue by sakimura** [oauth-wg/oauth-v2-1#189]
There has been a case where the signing key for the stateless JWT based access token was stolen and used by attacker to mint new access tokens. Since the token was stateless, meaning the resource servers verified the signature of the access token and if it was successful, the access token was accepted. This lead the attacker to be able to access resources at their will for an extended period as the signing key was not rotated. 

If such tokens are to be used, then the signing key MUST be rotated periodically to limit the exposed period. 

Also, the authorization server SHOULD keep track of the tokens issued and return error when a token that it did not issue with a valid signature was submitted to the token introspection endpoint.

**Comment by aaronpk** [comment]
https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-12#section-7.1.2

We will update this:

> A large range of threats can be mitigated by protecting the contents of the access token by using a digital signature, and by following best practices for signing key management such as periodic key rotation.

I don't think it makes sense to add your second recommendation.
