### ISSUE TITLE
Clarify scope of the spec

### ISSUE THREAD

**Issue by aaronpk** [oauth-wg/oauth-v2-1#25]
[From Vittorio](https://mailarchive.ietf.org/arch/msg/oauth/RP71xU8P4WLLIx0NcQMnw4gHScQ/):

> I wonder whether we should take the opportunity offered by OAuth2.1 to clarify frequent points of confusion about OAuth, by explicitly calling out in the introduction what is out of scope.
>
> For example: OAuth is not an identity protocol, as it doesn’t concern itself with how resource owners are authenticated; OAuth isn’t meant to address 1st party scenarios, although the reader is free to use it in that context as well; and so on.
>
> I believe there is value in adding this in the introduction rather than relegating it in some later considerations section, as the people who need this information the most rarely read past this point.

**Comment by aaronpk** [comment]
Related comment from vittorio:

> §1.8
> Should we say rich *delegated* authorization framework?

**Comment by aaronpk** [comment]
Also, the abstract likely needs to be updated. Currently it says:

> The OAuth 2.1 authorization framework enables a third-party application to obtain limited access to an HTTP service...

and we know that it's used for far more than third-party applications now.

**Comment by dickhardt** [comment]
I agree with both points. We should include what it is not, and ensure how it is used is included.

**Comment by aaronpk** [comment]
Most of this is resolved now, but could probably use some additional text in the intro on these two points:

* OAuth is not an identity protocol
* it doesn’t concern itself with how resource owners are authenticated

There is now some text that mentions the AS authenticating the resource owner, but could be more explicit to address this point.

**Comment by aaronpk** [comment]
Addressed in 125b9a41ed1c71a66f6b69aafa75e56af8323d60
