### ISSUE TITLE
add a reference to CORS support on the token endpoint

### ISSUE THREAD

**Issue by aaronpk** [oauth-wg/oauth-v2-1#43]
If the AS expects to be used by SPA clients it will need to support the necessary CORS headers. I think the best place to mention this is https://tools.ietf.org/html/draft-ietf-oauth-v2-1-00#section-3.2

**Comment by tlodderstedt** [comment]
Section 11 would be an alternative

**Comment by dickhardt** [comment]
I agree with adding a reference
