### ISSUE TITLE
Clarify limits and caveats on access token formats

### ISSUE THREAD

**Issue by aaronpk** [oauth-wg/oauth-v2-1#59]
Section 5.1

From Vittorio

> On the access_token parameter. Given the discussions we had for the JWT AT profile draft, I am wondering whether it should be called out here that the AT recipient is the RS, that the client should not expect to be able to parse the access_token, and that the AS is under no obligation to use a consistent AT encoding outside of what is negotiated with the RS. I don’t feel very strongly about this, or about where in the spec this should be called out, but it sure would have made life easier in those discussions- hence the comment.

**Comment by aaronpk** [comment]
I agree, but I would like to think further on where the best place for this description is.

**Comment by tlodderstedt** [comment]
I think 5.1 is the best place as the parameter is defined there.
